# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\mbs\zs_github\LifeBook\Chap 03-Tech\03.020-Python\uart_tool\sci_tool.ui'
#
# Created: Wed Aug 08 14:31:38 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1011, 704)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("link.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.DATA_RCV = QtGui.QLabel(self.centralwidget)
        self.DATA_RCV.setMaximumSize(QtCore.QSize(60, 16777215))
        self.DATA_RCV.setObjectName(_fromUtf8("DATA_RCV"))
        self.gridLayout_2.addWidget(self.DATA_RCV, 0, 0, 1, 1)
        self.sendnum_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.sendnum_lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sendnum_lineEdit.setReadOnly(True)
        self.sendnum_lineEdit.setObjectName(_fromUtf8("sendnum_lineEdit"))
        self.gridLayout_2.addWidget(self.sendnum_lineEdit, 0, 3, 1, 1)
        self.RecNumLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.RecNumLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.RecNumLineEdit.setReadOnly(True)
        self.RecNumLineEdit.setObjectName(_fromUtf8("RecNumLineEdit"))
        self.gridLayout_2.addWidget(self.RecNumLineEdit, 0, 1, 1, 1)
        self.clrcntbutton = QtGui.QPushButton(self.centralwidget)
        self.clrcntbutton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.clrcntbutton.setObjectName(_fromUtf8("clrcntbutton"))
        self.gridLayout_2.addWidget(self.clrcntbutton, 0, 4, 1, 1)
        self.DATA_SEND = QtGui.QLabel(self.centralwidget)
        self.DATA_SEND.setMaximumSize(QtCore.QSize(60, 16777215))
        self.DATA_SEND.setObjectName(_fromUtf8("DATA_SEND"))
        self.gridLayout_2.addWidget(self.DATA_SEND, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(538, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 1, 1, 1, 1)
        self.maintabwidget = QtGui.QTabWidget(self.centralwidget)
        self.maintabwidget.setAutoFillBackground(True)
        self.maintabwidget.setObjectName(_fromUtf8("maintabwidget"))
        self.scitooltab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scitooltab.sizePolicy().hasHeightForWidth())
        self.scitooltab.setSizePolicy(sizePolicy)
        self.scitooltab.setObjectName(_fromUtf8("scitooltab"))
        self.debugtab = QtGui.QTabWidget(self.scitooltab)
        self.debugtab.setEnabled(True)
        self.debugtab.setGeometry(QtCore.QRect(230, 10, 744, 591))
        self.debugtab.setTabShape(QtGui.QTabWidget.Triangular)
        self.debugtab.setObjectName(_fromUtf8("debugtab"))
        self.disstringtext = QtGui.QWidget()
        self.disstringtext.setObjectName(_fromUtf8("disstringtext"))
        self.distring = QtGui.QPlainTextEdit(self.disstringtext)
        self.distring.setGeometry(QtCore.QRect(1, 11, 651, 261))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(9)
        self.distring.setFont(font)
        self.distring.setAutoFillBackground(True)
        self.distring.setReadOnly(True)
        self.distring.setTabStopWidth(200)
        self.distring.setObjectName(_fromUtf8("distring"))
        self.widget = QtGui.QWidget(self.disstringtext)
        self.widget.setGeometry(QtCore.QRect(0, 290, 271, 251))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setMargin(2)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.x1_checkBox = QtGui.QCheckBox(self.widget)
        self.x1_checkBox.setObjectName(_fromUtf8("x1_checkBox"))
        self.horizontalLayout_20.addWidget(self.x1_checkBox)
        self.x1_low_line = QtGui.QLineEdit(self.widget)
        self.x1_low_line.setInputMask(_fromUtf8(""))
        self.x1_low_line.setMaxLength(6)
        self.x1_low_line.setObjectName(_fromUtf8("x1_low_line"))
        self.horizontalLayout_20.addWidget(self.x1_low_line)
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_20.addWidget(self.label_12)
        self.x1_high_line = QtGui.QLineEdit(self.widget)
        self.x1_high_line.setInputMask(_fromUtf8(""))
        self.x1_high_line.setMaxLength(6)
        self.x1_high_line.setObjectName(_fromUtf8("x1_high_line"))
        self.horizontalLayout_20.addWidget(self.x1_high_line)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.x1_plainTextEdit = QtGui.QPlainTextEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        self.x1_plainTextEdit.setFont(font)
        self.x1_plainTextEdit.setReadOnly(True)
        self.x1_plainTextEdit.setObjectName(_fromUtf8("x1_plainTextEdit"))
        self.verticalLayout_13.addWidget(self.x1_plainTextEdit)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(1)
        self.horizontalLayout_23.setMargin(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.x1clr_button = QtGui.QPushButton(self.widget)
        self.x1clr_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.x1clr_button.setObjectName(_fromUtf8("x1clr_button"))
        self.horizontalLayout_23.addWidget(self.x1clr_button)
        self.x1save_button = QtGui.QPushButton(self.widget)
        self.x1save_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.x1save_button.setObjectName(_fromUtf8("x1save_button"))
        self.horizontalLayout_23.addWidget(self.x1save_button)
        self.verticalLayout_13.addLayout(self.horizontalLayout_23)
        self.widget1 = QtGui.QWidget(self.disstringtext)
        self.widget1.setGeometry(QtCore.QRect(290, 320, 361, 221))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.debug_matplot_layout = QtGui.QHBoxLayout(self.widget1)
        self.debug_matplot_layout.setMargin(0)
        self.debug_matplot_layout.setObjectName(_fromUtf8("debug_matplot_layout"))
        self.widget2 = QtGui.QWidget(self.disstringtext)
        self.widget2.setGeometry(QtCore.QRect(291, 291, 361, 24))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.hexselec_radio = QtGui.QRadioButton(self.widget2)
        self.hexselec_radio.setObjectName(_fromUtf8("hexselec_radio"))
        self.gridLayout_4.addWidget(self.hexselec_radio, 0, 0, 1, 1)
        self.plotnum_Slider = QtGui.QSlider(self.widget2)
        self.plotnum_Slider.setMinimum(50)
        self.plotnum_Slider.setMaximum(1000)
        self.plotnum_Slider.setProperty("value", 500)
        self.plotnum_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.plotnum_Slider.setObjectName(_fromUtf8("plotnum_Slider"))
        self.gridLayout_4.addWidget(self.plotnum_Slider, 0, 2, 1, 1)
        self.plotnum_lineEdit = QtGui.QLineEdit(self.widget2)
        self.plotnum_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.plotnum_lineEdit.setReadOnly(True)
        self.plotnum_lineEdit.setObjectName(_fromUtf8("plotnum_lineEdit"))
        self.gridLayout_4.addWidget(self.plotnum_lineEdit, 0, 3, 1, 1)
        self.x1selec_radio = QtGui.QRadioButton(self.widget2)
        self.x1selec_radio.setObjectName(_fromUtf8("x1selec_radio"))
        self.gridLayout_4.addWidget(self.x1selec_radio, 0, 1, 1, 1)
        self.debugtab.addTab(self.disstringtext, _fromUtf8(""))
        self.dishextext = QtGui.QWidget()
        self.dishextext.setObjectName(_fromUtf8("dishextext"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dishextext)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.dishex = QtGui.QPlainTextEdit(self.dishextext)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(9)
        self.dishex.setFont(font)
        self.dishex.setReadOnly(True)
        self.dishex.setObjectName(_fromUtf8("dishex"))
        self.gridLayout_3.addWidget(self.dishex, 0, 0, 1, 1)
        self.debugtab.addTab(self.dishextext, _fromUtf8(""))
        self.sendtab = QtGui.QWidget()
        self.sendtab.setObjectName(_fromUtf8("sendtab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.sendtab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.line_2 = QtGui.QFrame(self.sendtab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_5.addWidget(self.line_2, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.sendtab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.sendclr_Button = QtGui.QPushButton(self.sendtab)
        self.sendclr_Button.setObjectName(_fromUtf8("sendclr_Button"))
        self.horizontalLayout_9.addWidget(self.sendclr_Button)
        spacerItem1 = QtGui.QSpacerItem(40, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.char_radioButton = QtGui.QRadioButton(self.sendtab)
        self.char_radioButton.setObjectName(_fromUtf8("char_radioButton"))
        self.horizontalLayout_9.addWidget(self.char_radioButton)
        self.hex_radioButton = QtGui.QRadioButton(self.sendtab)
        self.hex_radioButton.setAcceptDrops(False)
        self.hex_radioButton.setChecked(True)
        self.hex_radioButton.setObjectName(_fromUtf8("hex_radioButton"))
        self.horizontalLayout_9.addWidget(self.hex_radioButton)
        self.mainsend_Button = QtGui.QPushButton(self.sendtab)
        self.mainsend_Button.setObjectName(_fromUtf8("mainsend_Button"))
        self.horizontalLayout_9.addWidget(self.mainsend_Button)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.mainsend_Edit = QtGui.QTextEdit(self.sendtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainsend_Edit.sizePolicy().hasHeightForWidth())
        self.mainsend_Edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.mainsend_Edit.setFont(font)
        self.mainsend_Edit.setObjectName(_fromUtf8("mainsend_Edit"))
        self.gridLayout_5.addWidget(self.mainsend_Edit, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_4 = QtGui.QLabel(self.sendtab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_11.addWidget(self.label_4)
        self.cmd1_Edit = QtGui.QLineEdit(self.sendtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd1_Edit.sizePolicy().hasHeightForWidth())
        self.cmd1_Edit.setSizePolicy(sizePolicy)
        self.cmd1_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.cmd1_Edit.setFont(font)
        self.cmd1_Edit.setObjectName(_fromUtf8("cmd1_Edit"))
        self.horizontalLayout_11.addWidget(self.cmd1_Edit)
        self.cmd1sned_Button = QtGui.QPushButton(self.sendtab)
        self.cmd1sned_Button.setObjectName(_fromUtf8("cmd1sned_Button"))
        self.horizontalLayout_11.addWidget(self.cmd1sned_Button)
        self.gridLayout_5.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.line = QtGui.QFrame(self.sendtab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_5.addWidget(self.line, 4, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_5 = QtGui.QLabel(self.sendtab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_12.addWidget(self.label_5)
        self.cmd2_Edit = QtGui.QLineEdit(self.sendtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd2_Edit.sizePolicy().hasHeightForWidth())
        self.cmd2_Edit.setSizePolicy(sizePolicy)
        self.cmd2_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.cmd2_Edit.setFont(font)
        self.cmd2_Edit.setObjectName(_fromUtf8("cmd2_Edit"))
        self.horizontalLayout_12.addWidget(self.cmd2_Edit)
        self.cmd2sned_Button = QtGui.QPushButton(self.sendtab)
        self.cmd2sned_Button.setObjectName(_fromUtf8("cmd2sned_Button"))
        self.horizontalLayout_12.addWidget(self.cmd2sned_Button)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 5, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.sendtab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_5.addWidget(self.line_3, 6, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_6 = QtGui.QLabel(self.sendtab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_13.addWidget(self.label_6)
        self.cmd3_Edit = QtGui.QLineEdit(self.sendtab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmd3_Edit.sizePolicy().hasHeightForWidth())
        self.cmd3_Edit.setSizePolicy(sizePolicy)
        self.cmd3_Edit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(12)
        self.cmd3_Edit.setFont(font)
        self.cmd3_Edit.setObjectName(_fromUtf8("cmd3_Edit"))
        self.horizontalLayout_13.addWidget(self.cmd3_Edit)
        self.cmd3sned_Button = QtGui.QPushButton(self.sendtab)
        self.cmd3sned_Button.setObjectName(_fromUtf8("cmd3sned_Button"))
        self.horizontalLayout_13.addWidget(self.cmd3sned_Button)
        self.gridLayout_5.addLayout(self.horizontalLayout_13, 7, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.sendtab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_5.addWidget(self.line_4, 8, 0, 1, 1)
        self.debugtab.addTab(self.sendtab, _fromUtf8(""))
        self.debugdatatab = QtGui.QWidget()
        self.debugdatatab.setObjectName(_fromUtf8("debugdatatab"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.debugdatatab)
        self.verticalLayout_12.setSpacing(1)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.line_7 = QtGui.QFrame(self.debugdatatab)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_12.addWidget(self.line_7)
        self.debugtab.addTab(self.debugdatatab, _fromUtf8(""))
        self.matplottab = QtGui.QWidget()
        self.matplottab.setEnabled(False)
        self.matplottab.setObjectName(_fromUtf8("matplottab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.matplottab)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.Dataplot1 = QtGui.QHBoxLayout()
        self.Dataplot1.setSpacing(1)
        self.Dataplot1.setObjectName(_fromUtf8("Dataplot1"))
        self.verticalLayout_6.addLayout(self.Dataplot1)
        self.Dataplot2 = QtGui.QHBoxLayout()
        self.Dataplot2.setSpacing(1)
        self.Dataplot2.setObjectName(_fromUtf8("Dataplot2"))
        self.verticalLayout_6.addLayout(self.Dataplot2)
        self.Dataplot3 = QtGui.QHBoxLayout()
        self.Dataplot3.setSpacing(1)
        self.Dataplot3.setObjectName(_fromUtf8("Dataplot3"))
        self.verticalLayout_6.addLayout(self.Dataplot3)
        self.debugtab.addTab(self.matplottab, _fromUtf8(""))
        self.widget3 = QtGui.QWidget(self.scitooltab)
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.distext = QtGui.QTabWidget(self.widget3)
        self.distext.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distext.sizePolicy().hasHeightForWidth())
        self.distext.setSizePolicy(sizePolicy)
        self.distext.setMaximumSize(QtCore.QSize(194, 16777215))
        self.distext.setTabPosition(QtGui.QTabWidget.North)
        self.distext.setTabShape(QtGui.QTabWidget.Triangular)
        self.distext.setUsesScrollButtons(True)
        self.distext.setTabsClosable(False)
        self.distext.setMovable(False)
        self.distext.setObjectName(_fromUtf8("distext"))
        self.Protocoltab = QtGui.QWidget()
        self.Protocoltab.setEnabled(False)
        self.Protocoltab.setObjectName(_fromUtf8("Protocoltab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.Protocoltab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.checkBox = QtGui.QCheckBox(self.Protocoltab)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_7.addWidget(self.checkBox, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.Protocoltab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 0, 1, 1, 1)
        self.framenum_edit = QtGui.QLineEdit(self.Protocoltab)
        self.framenum_edit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.framenum_edit.setObjectName(_fromUtf8("framenum_edit"))
        self.gridLayout_7.addWidget(self.framenum_edit, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.Protocoltab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 1, 1, 1, 1)
        self.framehead_edit = QtGui.QLineEdit(self.Protocoltab)
        self.framehead_edit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.framehead_edit.setMaxLength(2)
        self.framehead_edit.setCursorPosition(2)
        self.framehead_edit.setObjectName(_fromUtf8("framehead_edit"))
        self.gridLayout_7.addWidget(self.framehead_edit, 1, 2, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.framesumcheck = QtGui.QCheckBox(self.Protocoltab)
        self.framesumcheck.setChecked(True)
        self.framesumcheck.setObjectName(_fromUtf8("framesumcheck"))
        self.horizontalLayout_8.addWidget(self.framesumcheck)
        self.label_3 = QtGui.QLabel(self.Protocoltab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.framend_edit = QtGui.QLineEdit(self.Protocoltab)
        self.framend_edit.setObjectName(_fromUtf8("framend_edit"))
        self.horizontalLayout_8.addWidget(self.framend_edit)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 1)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 2, 0, 1, 3)
        self.disprotocol = QtGui.QPlainTextEdit(self.Protocoltab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(11)
        self.disprotocol.setFont(font)
        self.disprotocol.setReadOnly(True)
        self.disprotocol.setObjectName(_fromUtf8("disprotocol"))
        self.gridLayout_7.addWidget(self.disprotocol, 3, 0, 1, 3)
        self.distext.addTab(self.Protocoltab, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.distext)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.clrcontentbutton = QtGui.QPushButton(self.widget3)
        self.clrcontentbutton.setObjectName(_fromUtf8("clrcontentbutton"))
        self.horizontalLayout_16.addWidget(self.clrcontentbutton)
        self.savecontentbutton = QtGui.QPushButton(self.widget3)
        self.savecontentbutton.setObjectName(_fromUtf8("savecontentbutton"))
        self.horizontalLayout_16.addWidget(self.savecontentbutton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.line_6 = QtGui.QFrame(self.widget3)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_3.addWidget(self.line_6)
        self.widget4 = QtGui.QWidget(self.scitooltab)
        self.widget4.setGeometry(QtCore.QRect(11, 401, 198, 165))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.gridLayout = QtGui.QGridLayout(self.widget4)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.portlabel = QtGui.QLabel(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portlabel.sizePolicy().hasHeightForWidth())
        self.portlabel.setSizePolicy(sizePolicy)
        self.portlabel.setMinimumSize(QtCore.QSize(60, 0))
        self.portlabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.portlabel.setFont(font)
        self.portlabel.setObjectName(_fromUtf8("portlabel"))
        self.horizontalLayout_4.addWidget(self.portlabel)
        spacerItem2 = QtGui.QSpacerItem(13, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.lineEdit = QtGui.QLineEdit(self.widget4)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMinimumSize(QtCore.QSize(60, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.portcomtext = QtGui.QLineEdit(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portcomtext.sizePolicy().hasHeightForWidth())
        self.portcomtext.setSizePolicy(sizePolicy)
        self.portcomtext.setMinimumSize(QtCore.QSize(35, 25))
        self.portcomtext.setMaximumSize(QtCore.QSize(40, 16777215))
        self.portcomtext.setMaxLength(2)
        self.portcomtext.setFrame(True)
        self.portcomtext.setEchoMode(QtGui.QLineEdit.Normal)
        self.portcomtext.setAlignment(QtCore.Qt.AlignCenter)
        self.portcomtext.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.portcomtext.setObjectName(_fromUtf8("portcomtext"))
        self.horizontalLayout_4.addWidget(self.portcomtext)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bandratelabel = QtGui.QLabel(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bandratelabel.sizePolicy().hasHeightForWidth())
        self.bandratelabel.setSizePolicy(sizePolicy)
        self.bandratelabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.bandratelabel.setFont(font)
        self.bandratelabel.setObjectName(_fromUtf8("bandratelabel"))
        self.horizontalLayout_3.addWidget(self.bandratelabel)
        spacerItem3 = QtGui.QSpacerItem(13, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.baudratecombo = QtGui.QComboBox(self.widget4)
        self.baudratecombo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudratecombo.sizePolicy().hasHeightForWidth())
        self.baudratecombo.setSizePolicy(sizePolicy)
        self.baudratecombo.setMinimumSize(QtCore.QSize(0, 25))
        self.baudratecombo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.baudratecombo.setBaseSize(QtCore.QSize(0, 0))
        self.baudratecombo.setEditable(False)
        self.baudratecombo.setObjectName(_fromUtf8("baudratecombo"))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.baudratecombo.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.baudratecombo)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.databitlabel = QtGui.QLabel(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databitlabel.sizePolicy().hasHeightForWidth())
        self.databitlabel.setSizePolicy(sizePolicy)
        self.databitlabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.databitlabel.setFont(font)
        self.databitlabel.setObjectName(_fromUtf8("databitlabel"))
        self.horizontalLayout_5.addWidget(self.databitlabel)
        spacerItem4 = QtGui.QSpacerItem(13, 13, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.databitcombo = QtGui.QComboBox(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databitcombo.sizePolicy().hasHeightForWidth())
        self.databitcombo.setSizePolicy(sizePolicy)
        self.databitcombo.setMinimumSize(QtCore.QSize(0, 25))
        self.databitcombo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.databitcombo.setObjectName(_fromUtf8("databitcombo"))
        self.databitcombo.addItem(_fromUtf8(""))
        self.databitcombo.addItem(_fromUtf8(""))
        self.databitcombo.addItem(_fromUtf8(""))
        self.databitcombo.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.databitcombo)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkbitlabel = QtGui.QLabel(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbitlabel.sizePolicy().hasHeightForWidth())
        self.checkbitlabel.setSizePolicy(sizePolicy)
        self.checkbitlabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkbitlabel.setFont(font)
        self.checkbitlabel.setObjectName(_fromUtf8("checkbitlabel"))
        self.horizontalLayout_6.addWidget(self.checkbitlabel)
        spacerItem5 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.checkbitcombo = QtGui.QComboBox(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbitcombo.sizePolicy().hasHeightForWidth())
        self.checkbitcombo.setSizePolicy(sizePolicy)
        self.checkbitcombo.setMinimumSize(QtCore.QSize(0, 25))
        self.checkbitcombo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.checkbitcombo.setObjectName(_fromUtf8("checkbitcombo"))
        self.checkbitcombo.addItem(_fromUtf8(""))
        self.checkbitcombo.addItem(_fromUtf8(""))
        self.checkbitcombo.addItem(_fromUtf8(""))
        self.checkbitcombo.addItem(_fromUtf8(""))
        self.checkbitcombo.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.checkbitcombo)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.stopbitlabel = QtGui.QLabel(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopbitlabel.sizePolicy().hasHeightForWidth())
        self.stopbitlabel.setSizePolicy(sizePolicy)
        self.stopbitlabel.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.stopbitlabel.setFont(font)
        self.stopbitlabel.setObjectName(_fromUtf8("stopbitlabel"))
        self.horizontalLayout_7.addWidget(self.stopbitlabel)
        spacerItem6 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.stopbitcombo = QtGui.QComboBox(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopbitcombo.sizePolicy().hasHeightForWidth())
        self.stopbitcombo.setSizePolicy(sizePolicy)
        self.stopbitcombo.setMinimumSize(QtCore.QSize(0, 25))
        self.stopbitcombo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.stopbitcombo.setObjectName(_fromUtf8("stopbitcombo"))
        self.stopbitcombo.addItem(_fromUtf8(""))
        self.stopbitcombo.addItem(_fromUtf8(""))
        self.stopbitcombo.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.stopbitcombo)
        self.gridLayout.addLayout(self.horizontalLayout_7, 4, 0, 1, 1)
        self.sciopenButton = QtGui.QPushButton(self.scitooltab)
        self.sciopenButton.setGeometry(QtCore.QRect(11, 573, 93, 28))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sciopenButton.sizePolicy().hasHeightForWidth())
        self.sciopenButton.setSizePolicy(sizePolicy)
        self.sciopenButton.setMaximumSize(QtCore.QSize(194, 16777215))
        self.sciopenButton.setCheckable(True)
        self.sciopenButton.setChecked(False)
        self.sciopenButton.setObjectName(_fromUtf8("sciopenButton"))
        self.maintabwidget.addTab(self.scitooltab, _fromUtf8(""))
        self.about_tab = QtGui.QWidget()
        self.about_tab.setObjectName(_fromUtf8("about_tab"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.about_tab)
        self.horizontalLayout_10.setSpacing(1)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.textBrowser = QtGui.QTextBrowser(self.about_tab)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.horizontalLayout_10.addWidget(self.textBrowser)
        self.maintabwidget.addTab(self.about_tab, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.maintabwidget, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.DATA_RCV.setBuddy(self.RecNumLineEdit)
        self.DATA_SEND.setBuddy(self.sendnum_lineEdit)

        self.retranslateUi(MainWindow)
        self.maintabwidget.setCurrentIndex(0)
        self.debugtab.setCurrentIndex(0)
        self.distext.setCurrentIndex(0)
        self.baudratecombo.setCurrentIndex(16)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.distext, self.distring)
        MainWindow.setTabOrder(self.distring, self.maintabwidget)
        MainWindow.setTabOrder(self.maintabwidget, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.framehead_edit)
        MainWindow.setTabOrder(self.framehead_edit, self.framenum_edit)
        MainWindow.setTabOrder(self.framenum_edit, self.framesumcheck)
        MainWindow.setTabOrder(self.framesumcheck, self.framend_edit)
        MainWindow.setTabOrder(self.framend_edit, self.disprotocol)
        MainWindow.setTabOrder(self.disprotocol, self.clrcontentbutton)
        MainWindow.setTabOrder(self.clrcontentbutton, self.savecontentbutton)
        MainWindow.setTabOrder(self.savecontentbutton, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.portcomtext)
        MainWindow.setTabOrder(self.portcomtext, self.baudratecombo)
        MainWindow.setTabOrder(self.baudratecombo, self.databitcombo)
        MainWindow.setTabOrder(self.databitcombo, self.checkbitcombo)
        MainWindow.setTabOrder(self.checkbitcombo, self.stopbitcombo)
        MainWindow.setTabOrder(self.stopbitcombo, self.sciopenButton)
        MainWindow.setTabOrder(self.sciopenButton, self.debugtab)
        MainWindow.setTabOrder(self.debugtab, self.char_radioButton)
        MainWindow.setTabOrder(self.char_radioButton, self.hex_radioButton)
        MainWindow.setTabOrder(self.hex_radioButton, self.mainsend_Button)
        MainWindow.setTabOrder(self.mainsend_Button, self.mainsend_Edit)
        MainWindow.setTabOrder(self.mainsend_Edit, self.cmd1_Edit)
        MainWindow.setTabOrder(self.cmd1_Edit, self.cmd1sned_Button)
        MainWindow.setTabOrder(self.cmd1sned_Button, self.cmd2_Edit)
        MainWindow.setTabOrder(self.cmd2_Edit, self.cmd2sned_Button)
        MainWindow.setTabOrder(self.cmd2sned_Button, self.cmd3_Edit)
        MainWindow.setTabOrder(self.cmd3_Edit, self.cmd3sned_Button)
        MainWindow.setTabOrder(self.cmd3sned_Button, self.x1_checkBox)
        MainWindow.setTabOrder(self.x1_checkBox, self.x1_low_line)
        MainWindow.setTabOrder(self.x1_low_line, self.x1_high_line)
        MainWindow.setTabOrder(self.x1_high_line, self.x1_plainTextEdit)
        MainWindow.setTabOrder(self.x1_plainTextEdit, self.x1clr_button)
        MainWindow.setTabOrder(self.x1clr_button, self.x1save_button)
        MainWindow.setTabOrder(self.x1save_button, self.hexselec_radio)
        MainWindow.setTabOrder(self.hexselec_radio, self.plotnum_Slider)
        MainWindow.setTabOrder(self.plotnum_Slider, self.plotnum_lineEdit)
        MainWindow.setTabOrder(self.plotnum_lineEdit, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.RecNumLineEdit)
        MainWindow.setTabOrder(self.RecNumLineEdit, self.sendnum_lineEdit)
        MainWindow.setTabOrder(self.sendnum_lineEdit, self.clrcntbutton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "DebugTool_V1.0", None))
        self.DATA_RCV.setText(_translate("MainWindow", "RECV:", None))
        self.sendnum_lineEdit.setText(_translate("MainWindow", "0", None))
        self.RecNumLineEdit.setText(_translate("MainWindow", "0", None))
        self.clrcntbutton.setText(_translate("MainWindow", "CLR_CNT", None))
        self.DATA_SEND.setText(_translate("MainWindow", "SEND:", None))
        self.x1_checkBox.setText(_translate("MainWindow", "Rng:", None))
        self.x1_low_line.setText(_translate("MainWindow", "-10", None))
        self.label_12.setText(_translate("MainWindow", "< X1 <", None))
        self.x1_high_line.setText(_translate("MainWindow", "10", None))
        self.x1clr_button.setText(_translate("MainWindow", "Clear", None))
        self.x1save_button.setText(_translate("MainWindow", "Save", None))
        self.hexselec_radio.setText(_translate("MainWindow", "Hex Graph", None))
        self.plotnum_lineEdit.setInputMask(_translate("MainWindow", "9999; ", None))
        self.plotnum_lineEdit.setText(_translate("MainWindow", "500", None))
        self.x1selec_radio.setText(_translate("MainWindow", "X1 Graph", None))
        self.debugtab.setTabText(self.debugtab.indexOf(self.disstringtext), _translate("MainWindow", "String", None))
        self.debugtab.setTabText(self.debugtab.indexOf(self.dishextext), _translate("MainWindow", "Hex", None))
        self.label_10.setText(_translate("MainWindow", "Format:", None))
        self.sendclr_Button.setText(_translate("MainWindow", "CLR_DATA", None))
        self.char_radioButton.setText(_translate("MainWindow", "Char", None))
        self.hex_radioButton.setText(_translate("MainWindow", "Hex", None))
        self.mainsend_Button.setText(_translate("MainWindow", "SEND", None))
        self.label_4.setText(_translate("MainWindow", "CMD1:", None))
        self.cmd1sned_Button.setText(_translate("MainWindow", "Send_1", None))
        self.label_5.setText(_translate("MainWindow", "CMD2:", None))
        self.cmd2sned_Button.setText(_translate("MainWindow", "Send_2", None))
        self.label_6.setText(_translate("MainWindow", "CMD3:", None))
        self.cmd3sned_Button.setText(_translate("MainWindow", "Send_3", None))
        self.debugtab.setTabText(self.debugtab.indexOf(self.sendtab), _translate("MainWindow", "Send", None))
        self.debugtab.setTabText(self.debugtab.indexOf(self.debugdatatab), _translate("MainWindow", "DebugData", None))
        self.debugtab.setTabText(self.debugtab.indexOf(self.matplottab), _translate("MainWindow", "Dataplot", None))
        self.checkBox.setText(_translate("MainWindow", "Enable", None))
        self.label_2.setText(_translate("MainWindow", "Data:", None))
        self.framenum_edit.setInputMask(_translate("MainWindow", "99; ", None))
        self.framenum_edit.setText(_translate("MainWindow", "4", None))
        self.label.setText(_translate("MainWindow", "Header:", None))
        self.framehead_edit.setInputMask(_translate("MainWindow", "HH; ", None))
        self.framehead_edit.setText(_translate("MainWindow", "FF", None))
        self.framesumcheck.setText(_translate("MainWindow", "Check", None))
        self.label_3.setText(_translate("MainWindow", "Tail:", None))
        self.framend_edit.setInputMask(_translate("MainWindow", "HH; ", None))
        self.framend_edit.setText(_translate("MainWindow", "FF", None))
        self.distext.setTabText(self.distext.indexOf(self.Protocoltab), _translate("MainWindow", "Protocol", None))
        self.clrcontentbutton.setText(_translate("MainWindow", "CLR_RCV", None))
        self.savecontentbutton.setText(_translate("MainWindow", "SAVE_AS", None))
        self.portlabel.setText(_translate("MainWindow", "Port：", None))
        self.lineEdit.setText(_translate("MainWindow", "Com Port", None))
        self.portcomtext.setInputMask(_translate("MainWindow", "99; ", None))
        self.portcomtext.setText(_translate("MainWindow", "4", None))
        self.bandratelabel.setText(_translate("MainWindow", "Baudrate：", None))
        self.baudratecombo.setItemText(0, _translate("MainWindow", "50", None))
        self.baudratecombo.setItemText(1, _translate("MainWindow", "75", None))
        self.baudratecombo.setItemText(2, _translate("MainWindow", "110", None))
        self.baudratecombo.setItemText(3, _translate("MainWindow", "134", None))
        self.baudratecombo.setItemText(4, _translate("MainWindow", "150", None))
        self.baudratecombo.setItemText(5, _translate("MainWindow", "200", None))
        self.baudratecombo.setItemText(6, _translate("MainWindow", "300", None))
        self.baudratecombo.setItemText(7, _translate("MainWindow", "600", None))
        self.baudratecombo.setItemText(8, _translate("MainWindow", "1200", None))
        self.baudratecombo.setItemText(9, _translate("MainWindow", "1800", None))
        self.baudratecombo.setItemText(10, _translate("MainWindow", "2400", None))
        self.baudratecombo.setItemText(11, _translate("MainWindow", "4800", None))
        self.baudratecombo.setItemText(12, _translate("MainWindow", "9600", None))
        self.baudratecombo.setItemText(13, _translate("MainWindow", "19200", None))
        self.baudratecombo.setItemText(14, _translate("MainWindow", "38400", None))
        self.baudratecombo.setItemText(15, _translate("MainWindow", "57600", None))
        self.baudratecombo.setItemText(16, _translate("MainWindow", "115200", None))
        self.databitlabel.setText(_translate("MainWindow", "Data Bits：", None))
        self.databitcombo.setItemText(0, _translate("MainWindow", "8bit", None))
        self.databitcombo.setItemText(1, _translate("MainWindow", "7bit", None))
        self.databitcombo.setItemText(2, _translate("MainWindow", "6bit", None))
        self.databitcombo.setItemText(3, _translate("MainWindow", "5bit", None))
        self.checkbitlabel.setText(_translate("MainWindow", "Parity：", None))
        self.checkbitcombo.setItemText(0, _translate("MainWindow", "None", None))
        self.checkbitcombo.setItemText(1, _translate("MainWindow", "Even", None))
        self.checkbitcombo.setItemText(2, _translate("MainWindow", "Odd", None))
        self.checkbitcombo.setItemText(3, _translate("MainWindow", "Mark1", None))
        self.checkbitcombo.setItemText(4, _translate("MainWindow", "Space0", None))
        self.stopbitlabel.setText(_translate("MainWindow", "Stop Bits：", None))
        self.stopbitcombo.setItemText(0, _translate("MainWindow", "1bit", None))
        self.stopbitcombo.setItemText(1, _translate("MainWindow", "1.5bit", None))
        self.stopbitcombo.setItemText(2, _translate("MainWindow", "2bit", None))
        self.sciopenButton.setText(_translate("MainWindow", "OPEN_COMM", None))
        self.maintabwidget.setTabText(self.maintabwidget.indexOf(self.scitooltab), _translate("MainWindow", "SciTool", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.5pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:12pt;\">    PComm-Tool for motor control debuging. huamg.</span></p></body></html>", None))
        self.maintabwidget.setTabText(self.maintabwidget.indexOf(self.about_tab), _translate("MainWindow", "About", None))

